2017-10-17 09:33:49,960 > INFO > Starting MonitoringEngine
2017-10-17 09:33:50,914 > INFO > Starting MonitoringEngine
2017-10-17 09:42:52,221 > INFO > Starting MonitoringEngine
2017-10-17 09:42:53,154 > INFO > Starting MonitoringEngine
2017-10-19 07:59:06,615 > INFO > Starting MonitoringEngine
2017-10-19 07:59:08,042 > INFO > Starting MonitoringEngine
2017-10-19 08:19:48,439 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:20:42,646 > INFO > Starting MonitoringEngine
2017-10-19 08:20:53,176 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:23:14,579 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:25:20,417 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:31:44,599 > INFO > Starting MonitoringEngine
2017-10-19 08:31:54,324 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:33:54,366 > INFO > Starting MonitoringEngine
2017-10-19 08:35:44,807 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 11:45:21,817 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:47:08,257 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:48:18,261 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:49:32,307 > INFO > Starting MonitoringEngine
2017-10-19 11:50:18,562 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:53:42,290 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:53:54,001 > INFO > Starting MonitoringEngine
2017-10-19 11:57:42,327 > INFO > Starting MonitoringEngine
2017-10-19 11:57:55,245 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:59:06,990 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:00:18,776 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\n- ci'
2017-10-19 12:00:21,949 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:02:53,525 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:08:26,951 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:09:41,718 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:10:31,682 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:11:55,831 > INFO > Starting MonitoringEngine
2017-10-21 11:10:00,965 > INFO > Starting MonitoringEngine
2017-10-21 11:10:02,714 > INFO > Starting MonitoringEngine
2017-10-21 11:54:29,848 > INFO > Starting MonitoringEngine
2017-10-21 11:54:34,969 > INFO > Starting MonitoringEngine
2017-10-21 11:54:43,240 > INFO > Starting MonitoringEngine
2017-10-21 11:56:49,422 > INFO > Starting MonitoringEngine
2017-10-21 12:06:08,141 > INFO > Starting MonitoringEngine
2017-10-21 12:06:37,631 > INFO > Starting MonitoringEngine
2017-10-21 18:40:32,384 > INFO > Starting MonitoringEngine
2017-10-21 18:40:34,859 > INFO > Starting MonitoringEngine
2017-10-21 18:44:22,941 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:46:46,369 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:48:54,762 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:52:59,079 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 08:49:35,932 > INFO > Starting MonitoringEngine
2017-10-21 08:49:36,628 > INFO > Starting MonitoringEngine
2017-10-21 08:50:19,892 > INFO > Starting MonitoringEngine
2017-10-21 08:50:20,296 > INFO > Starting MonitoringEngine
2017-10-21 10:54:28,388 > INFO > Starting MonitoringEngine
2017-10-21 10:54:29,021 > INFO > Starting MonitoringEngine
2017-10-22 02:47:50,940 > INFO > Starting MonitoringEngine
2017-10-22 02:47:52,066 > INFO > Starting MonitoringEngine
2017-10-22 02:52:50,540 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 03:05:49,526 > INFO > Starting MonitoringEngine
2017-10-22 03:05:50,011 > INFO > Starting MonitoringEngine
2017-10-22 03:08:30,032 > INFO > Starting MonitoringEngine
2017-10-22 03:08:30,478 > INFO > Starting MonitoringEngine
2017-10-22 05:22:31,779 > INFO > Starting MonitoringEngine
2017-10-22 05:37:47,330 > INFO > Starting MonitoringEngine
2017-10-22 06:36:32,336 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 07:24:59,806 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 07:31:37,402 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 07:33:42,354 > INFO > Starting MonitoringEngine
2017-10-22 07:34:00,966 > INFO > Starting MonitoringEngine
2017-10-22 07:34:04,606 > INFO > Starting MonitoringEngine
2017-10-22 07:34:32,660 > INFO > Starting MonitoringEngine
2017-10-22 07:35:13,693 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-25 06:13:40,758 > INFO > Starting MonitoringEngine
2017-10-25 06:13:41,517 > INFO > Starting MonitoringEngine
2017-10-25 06:14:11,628 > INFO > Starting MonitoringEngine
2017-10-25 06:14:12,097 > INFO > Starting MonitoringEngine
2017-10-25 10:53:07,741 > INFO > Starting MonitoringEngine
2017-10-25 10:53:08,941 > INFO > Starting MonitoringEngine
2017-10-25 10:53:45,006 > INFO > Starting MonitoringEngine
2017-10-25 10:55:07,176 > INFO > Starting MonitoringEngine
2017-10-25 10:55:39,817 > INFO > Starting MonitoringEngine
2017-10-25 10:57:56,691 > INFO > Starting MonitoringEngine
2017-10-25 10:58:09,745 > INFO > Starting MonitoringEngine
2017-10-25 10:58:27,844 > INFO > Starting MonitoringEngine
2017-10-25 12:26:04,775 > INFO > Starting MonitoringEngine
2017-10-25 12:26:06,351 > INFO > Starting MonitoringEngine
2017-10-25 12:33:15,217 > INFO > Starting MonitoringEngine
2017-10-25 12:33:15,625 > INFO > Starting MonitoringEngine
2017-10-25 12:35:12,771 > INFO > Starting MonitoringEngine
2017-10-25 12:42:43,396 > INFO > Starting MonitoringEngine
2017-10-25 12:43:49,530 > INFO > Starting MonitoringEngine
2017-10-25 12:45:13,680 > INFO > Starting MonitoringEngine
2017-10-25 12:45:36,676 > INFO > Starting MonitoringEngine
2017-10-25 12:45:54,659 > INFO > Starting MonitoringEngine
2017-10-25 12:46:00,907 > INFO > Starting MonitoringEngine
2017-10-25 12:51:24,784 > INFO > Starting MonitoringEngine
2017-10-25 12:51:25,206 > INFO > Starting MonitoringEngine
2017-10-25 12:52:14,326 > INFO > Starting MonitoringEngine
2017-10-25 12:59:04,462 > INFO > Starting MonitoringEngine
2017-10-25 12:59:04,873 > INFO > Starting MonitoringEngine
2017-10-25 13:09:06,107 > INFO > Starting MonitoringEngine
2017-10-25 13:15:00,393 > INFO > Starting MonitoringEngine
2017-10-25 13:16:50,606 > INFO > Starting MonitoringEngine
2017-10-25 13:18:46,347 > INFO > Starting MonitoringEngine
2017-10-25 13:19:12,434 > INFO > Starting MonitoringEngine
2017-10-25 13:19:26,979 > INFO > Starting MonitoringEngine
2017-10-25 13:20:04,045 > INFO > Starting MonitoringEngine
2017-10-25 13:20:28,081 > INFO > Starting MonitoringEngine
2017-10-25 13:20:54,122 > INFO > Starting MonitoringEngine
2017-10-25 13:21:54,361 > INFO > Starting MonitoringEngine
2017-10-25 13:22:36,068 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-25 13:23:09,752 > INFO > Starting MonitoringEngine
2017-10-26 19:37:58,892 > INFO > Starting MonitoringEngine
2017-10-26 19:37:59,727 > INFO > Starting MonitoringEngine
2017-10-26 20:04:02,195 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-26 20:07:05,296 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:21:00,598 > INFO > Starting MonitoringEngine
2017-10-27 20:21:01,293 > INFO > Starting MonitoringEngine
2017-10-27 20:21:28,470 > INFO > Starting MonitoringEngine
2017-10-27 20:21:28,865 > INFO > Starting MonitoringEngine
2017-10-27 20:22:30,215 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:23:27,309 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:24:16,495 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:26:05,070 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:26:43,267 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:29:19,705 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:44:11,966 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 20:57:52,057 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 21:10:44,772 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 21:19:54,037 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-27 21:20:06,416 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 01:22:17,023 > INFO > Starting MonitoringEngine
2017-10-28 01:22:18,485 > INFO > Starting MonitoringEngine
2017-10-28 02:20:53,503 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 04:23:47,879 > ERROR > merge_js_yaml
Traceback (most recent call last):
  File "websnap.py", line 410, in merge_js_yaml
    netsnap = yaml_js.get("networksnap")
AttributeError: 'NoneType' object has no attribute 'get'
2017-10-28 04:25:44,816 > ERROR > merge_js_yaml
Traceback (most recent call last):
  File "websnap.py", line 410, in merge_js_yaml
    netsnap = yaml_js.get("networksnap")
AttributeError: 'NoneType' object has no attribute 'get'
2017-10-28 04:28:49,405 > ERROR > merge_js_yaml
Traceback (most recent call last):
  File "websnap.py", line 410, in merge_js_yaml
    netsnap = yaml_js.get("networksnap")
AttributeError: 'NoneType' object has no attribute 'get'
2017-10-28 05:09:44,491 > ERROR > merge_js_yaml
Traceback (most recent call last):
  File "websnap.py", line 410, in merge_js_yaml
    netsnap = yaml_js.get("networksnap")
AttributeError: 'list' object has no attribute 'get'
2017-10-28 05:15:31,097 > INFO > Starting MonitoringEngine
2017-10-28 05:16:02,161 > INFO > Starting MonitoringEngine
2017-10-28 05:16:08,135 > INFO > Starting MonitoringEngine
2017-10-28 05:16:35,895 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 05:17:16,476 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 05:23:54,246 > INFO > Starting MonitoringEngine
2017-10-28 05:24:08,272 > INFO > Starting MonitoringEngine
2017-10-28 05:24:12,254 > INFO > Starting MonitoringEngine
2017-10-28 05:24:16,213 > INFO > Starting MonitoringEngine
2017-10-28 05:25:46,390 > INFO > Starting MonitoringEngine
2017-10-28 05:25:53,375 > INFO > Starting MonitoringEngine
2017-10-28 05:26:12,360 > INFO > Starting MonitoringEngine
2017-10-28 05:26:16,372 > INFO > Starting MonitoringEngine
2017-10-28 05:26:24,204 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 05:28:44,187 > INFO > Starting MonitoringEngine
2017-10-28 10:17:48,674 > INFO > Starting MonitoringEngine
2017-10-28 10:17:49,580 > INFO > Starting MonitoringEngine
2017-10-28 10:18:52,265 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: '/home/networksnap/div/network_snap/input_file/default.xlsx'
2017-10-28 10:19:06,798 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:19:57,128 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: '/home/networksnap/div/network_snap/input_file/default.xlsx'
2017-10-28 10:20:28,838 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:20:52,650 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:35:13,130 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: '/home/networksnap/div/network_snap/input_file/default.xlsx'
2017-10-28 10:36:49,667 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:47:54,735 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:48:25,958 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\n\n- f'
2017-10-28 10:54:33,456 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:57:00,681 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 10:59:01,390 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:04:31,775 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:06:39,851 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:13:17,003 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:14:23,677 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:14:53,082 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\n\n- f'
2017-10-28 11:15:03,905 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:16:33,055 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:35:30,241 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 11:36:54,718 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\n\n- f'
2017-10-28 11:37:18,349 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 452, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 22:16:34,066 > INFO > Starting MonitoringEngine
2017-10-28 22:16:34,674 > INFO > Starting MonitoringEngine
2017-10-28 22:49:07,483 > INFO > Starting MonitoringEngine
2017-10-28 22:49:11,459 > INFO > Starting MonitoringEngine
2017-10-28 22:49:22,467 > INFO > Starting MonitoringEngine
2017-10-28 22:49:43,494 > INFO > Starting MonitoringEngine
2017-10-28 22:49:50,226 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 22:51:11,170 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 23:27:37,868 > INFO > Starting MonitoringEngine
2017-10-28 23:27:51,972 > INFO > Starting MonitoringEngine
2017-10-28 23:28:27,639 > ERROR > merge_js_yaml
Traceback (most recent call last):
  File "websnap.py", line 440, in merge_js_yaml
    new_obj = {"Objects":[{"function":json.loads(js_fun),"input":js_inp}],"IP":js_ip,"Hostname":js_host}
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2017-10-28 23:29:57,104 > ERROR > merge_js_yaml
Traceback (most recent call last):
  File "websnap.py", line 440, in merge_js_yaml
    new_obj = {"Objects":[{"function":json.loads(js_fun),"input":js_inp}],"IP":js_ip,"Hostname":js_host}
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2017-10-28 23:30:14,752 > INFO > Starting MonitoringEngine
2017-10-28 23:30:24,253 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 23:31:39,265 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 23:38:11,329 > INFO > Starting MonitoringEngine
2017-10-28 23:38:47,123 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 23:39:33,537 > INFO > Starting MonitoringEngine
2017-10-28 23:39:56,552 > INFO > Starting MonitoringEngine
2017-10-28 23:40:11,158 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-28 23:40:45,357 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 23:41:22,893 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 23:47:36,681 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-28 23:52:53,466 > INFO > Starting MonitoringEngine
2017-10-29 00:11:54,871 > INFO > Starting MonitoringEngine
2017-10-29 00:12:02,392 > INFO > Starting MonitoringEngine
2017-10-29 00:12:09,431 > INFO > Starting MonitoringEngine
2017-10-29 00:12:24,495 > INFO > Starting MonitoringEngine
2017-10-29 00:12:29,295 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-29 00:13:17,773 > INFO > Starting MonitoringEngine
2017-10-29 00:14:26,858 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 116, in open_workbook
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: '/home/networksnap/div/network_snap/input_file/default.xlsx'
2017-10-29 00:14:33,430 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-29 00:22:02,026 > INFO > Starting MonitoringEngine
2017-10-29 00:24:43,503 > INFO > Starting MonitoringEngine
2017-10-29 00:24:51,530 > INFO > Starting MonitoringEngine
2017-10-29 00:25:00,439 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-29 00:26:53,355 > INFO > Starting MonitoringEngine
2017-10-29 00:28:48,613 > INFO > Starting MonitoringEngine
2017-10-29 00:28:59,631 > INFO > Starting MonitoringEngine
2017-10-29 00:29:27,667 > INFO > Starting MonitoringEngine
2017-10-29 00:37:33,213 > INFO > Starting MonitoringEngine
2017-10-29 00:37:46,777 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-29 00:38:55,421 > INFO > Starting MonitoringEngine
2017-10-29 00:39:03,078 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-29 00:40:24,638 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-10-29 12:01:32,034 > INFO > Starting MonitoringEngine
2017-10-29 12:01:32,552 > INFO > Starting MonitoringEngine
2017-10-29 12:02:05,695 > INFO > Starting MonitoringEngine
2017-10-29 12:02:06,232 > INFO > Starting MonitoringEngine
2017-10-29 12:03:15,152 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 454, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found 'credenti'
2017-11-02 21:17:30,750 > INFO > Starting MonitoringEngine
2017-11-02 21:17:32,569 > INFO > Starting MonitoringEngine
2017-11-02 21:58:51,211 > INFO > Starting MonitoringEngine
2017-11-02 21:59:00,572 > INFO > Starting MonitoringEngine
2017-11-04 11:38:23,369 > INFO > Starting MonitoringEngine
2017-11-04 11:38:27,805 > INFO > Starting MonitoringEngine
2017-11-04 11:40:11,587 > INFO > Starting MonitoringEngine
2017-11-04 11:40:14,184 > INFO > Starting MonitoringEngine
2017-11-08 00:32:17,253 > INFO > Starting MonitoringEngine
2017-11-08 00:32:21,221 > INFO > Starting MonitoringEngine
2017-11-08 00:36:49,826 > INFO > Starting MonitoringEngine
2017-11-08 00:54:47,926 > INFO > Starting MonitoringEngine
2017-11-08 00:55:18,699 > INFO > Starting MonitoringEngine
2017-11-08 00:55:20,583 > INFO > Starting MonitoringEngine
2017-11-08 00:56:03,245 > INFO > Starting MonitoringEngine
2017-11-08 00:56:15,623 > INFO > Starting MonitoringEngine
2017-11-08 00:56:25,997 > INFO > Starting MonitoringEngine
2017-11-08 00:56:29,357 > INFO > Starting MonitoringEngine
2017-11-08 00:58:11,008 > INFO > Starting MonitoringEngine
2017-11-08 01:01:47,201 > INFO > Starting MonitoringEngine
2017-11-08 01:04:09,494 > INFO > Starting MonitoringEngine
2017-11-08 01:06:10,047 > INFO > Starting MonitoringEngine
2017-11-08 01:06:34,811 > INFO > Starting MonitoringEngine
2017-11-08 01:07:08,278 > INFO > Starting MonitoringEngine
2017-11-08 01:07:54,753 > INFO > Starting MonitoringEngine
2017-11-08 01:08:21,246 > INFO > Starting MonitoringEngine
2017-11-08 01:08:31,742 > INFO > Starting MonitoringEngine
2017-11-08 01:10:24,364 > INFO > Starting MonitoringEngine
2017-11-08 01:10:58,046 > INFO > Starting MonitoringEngine
2017-11-08 01:11:05,512 > INFO > Starting MonitoringEngine
2017-11-08 01:11:47,994 > INFO > Starting MonitoringEngine
2017-11-08 01:12:10,404 > INFO > Starting MonitoringEngine
2017-11-08 01:12:45,873 > INFO > Starting MonitoringEngine
2017-11-08 01:12:52,361 > INFO > Starting MonitoringEngine
2017-11-08 01:13:47,381 > INFO > Starting MonitoringEngine
2017-11-08 01:15:28,593 > INFO > Starting MonitoringEngine
2017-11-08 01:15:30,379 > INFO > Starting MonitoringEngine
2017-11-08 01:16:18,440 > INFO > Starting MonitoringEngine
2017-11-08 01:16:59,953 > INFO > Starting MonitoringEngine
2017-11-08 01:17:56,003 > INFO > Starting MonitoringEngine
2017-11-08 01:20:51,358 > INFO > Starting MonitoringEngine
2017-11-08 01:21:05,775 > INFO > Starting MonitoringEngine
2017-11-08 01:21:10,200 > INFO > Starting MonitoringEngine
2017-11-08 01:21:34,727 > INFO > Starting MonitoringEngine
2017-11-08 01:21:43,173 > INFO > Starting MonitoringEngine
2017-11-08 01:21:49,544 > INFO > Starting MonitoringEngine
2017-11-08 01:21:57,968 > INFO > Starting MonitoringEngine
2017-11-08 01:22:09,388 > INFO > Starting MonitoringEngine
2017-11-08 01:22:14,750 > INFO > Starting MonitoringEngine
2017-11-08 01:22:22,172 > INFO > Starting MonitoringEngine
2017-11-08 01:23:01,763 > INFO > Starting MonitoringEngine
2017-11-08 01:24:31,936 > INFO > Starting MonitoringEngine
2017-11-08 01:42:42,614 > INFO > Starting MonitoringEngine
2017-11-08 01:42:44,402 > INFO > Starting MonitoringEngine
2017-11-08 01:44:14,491 > INFO > Starting MonitoringEngine
2017-11-08 01:44:55,190 > INFO > Starting MonitoringEngine
2017-11-08 01:46:08,357 > INFO > Starting MonitoringEngine
2017-11-08 01:47:20,480 > ERROR > sqlget_output
Traceback (most recent call last):
  File "websnap.py", line 51, in sqlget_output
    mcollection = mdb['OUTPUT']
NameError: global name 'mdb' is not defined
2017-11-08 01:47:45,754 > INFO > Starting MonitoringEngine
2017-11-08 01:47:58,528 > INFO > Starting MonitoringEngine
2017-11-08 01:47:58,560 > ERROR > sqlget_output
Traceback (most recent call last):
  File "websnap.py", line 51, in sqlget_output
    mcollection = mdb['OUTPUT']
NameError: global name 'mdb' is not defined
2017-11-08 01:48:25,007 > INFO > Starting MonitoringEngine
2017-11-08 01:48:54,508 > INFO > Starting MonitoringEngine
2017-11-08 01:49:00,041 > INFO > Starting MonitoringEngine
2017-11-08 01:49:14,529 > INFO > Starting MonitoringEngine
2017-11-08 01:49:52,042 > INFO > Starting MonitoringEngine
2017-11-08 01:49:52,859 > ERROR > sqlget_output
Traceback (most recent call last):
  File "websnap.py", line 51, in sqlget_output
    mcollection = mdb['OUTPUT']
NameError: global name 'mdb' is not defined
2017-11-08 01:51:52,619 > ERROR > sqlget_output
Traceback (most recent call last):
  File "websnap.py", line 51, in sqlget_output
    mcollection = mdb['OUTPUT']
NameError: global name 'mdb' is not defined
2017-11-08 01:53:16,965 > INFO > Starting MonitoringEngine
2017-11-08 01:53:19,056 > ERROR > sqlget_output
Traceback (most recent call last):
  File "websnap.py", line 51, in sqlget_output
    mcollection = mdb['OUTPUT']
NameError: global name 'mdb' is not defined
2017-11-08 01:54:57,704 > INFO > Starting MonitoringEngine
2017-11-08 01:55:29,212 > INFO > Starting MonitoringEngine
2017-11-08 01:59:39,637 > INFO > Starting MonitoringEngine
2017-11-08 02:00:10,068 > INFO > Starting MonitoringEngine
2017-11-08 02:10:34,695 > INFO > Starting MonitoringEngine
2017-11-08 02:14:39,319 > INFO > Starting MonitoringEngine
2017-11-08 02:18:45,862 > INFO > Starting MonitoringEngine
2017-11-08 02:19:42,947 > INFO > Starting MonitoringEngine
2017-11-08 02:19:48,333 > INFO > Starting MonitoringEngine
2017-11-08 02:20:15,830 > INFO > Starting MonitoringEngine
2017-11-08 02:20:22,275 > INFO > Starting MonitoringEngine
2017-11-08 02:21:06,780 > INFO > Starting MonitoringEngine
2017-11-08 02:21:37,211 > INFO > Starting MonitoringEngine
2017-11-08 02:52:18,894 > INFO > Starting MonitoringEngine
2017-11-08 02:52:20,732 > INFO > Starting MonitoringEngine
2017-11-08 02:54:43,074 > INFO > Starting MonitoringEngine
2017-11-08 02:54:48,725 > INFO > Starting MonitoringEngine
2017-11-08 02:55:11,169 > INFO > Starting MonitoringEngine
2017-11-08 02:58:24,120 > INFO > Starting MonitoringEngine
2017-11-08 02:59:30,170 > INFO > Starting MonitoringEngine
2017-11-08 03:00:06,637 > INFO > Starting MonitoringEngine
2017-11-08 03:01:43,292 > INFO > Starting MonitoringEngine
2017-11-08 03:03:44,220 > INFO > Starting MonitoringEngine
2017-11-08 03:03:50,654 > INFO > Starting MonitoringEngine
2017-11-08 03:04:16,327 > INFO > Starting MonitoringEngine
2017-11-08 03:06:55,568 > INFO > Starting MonitoringEngine
2017-11-08 03:07:03,957 > INFO > Starting MonitoringEngine
2017-11-08 03:07:58,787 > INFO > Starting MonitoringEngine
2017-11-08 03:08:32,282 > INFO > Starting MonitoringEngine
2017-11-08 03:08:50,751 > INFO > Starting MonitoringEngine
2017-11-08 03:09:13,223 > INFO > Starting MonitoringEngine
2017-11-08 03:10:03,274 > INFO > Starting MonitoringEngine
2017-11-08 03:11:52,162 > INFO > Starting MonitoringEngine
2017-11-08 03:12:11,647 > INFO > Starting MonitoringEngine
2017-11-08 03:12:40,147 > INFO > Starting MonitoringEngine
2017-11-08 03:13:05,629 > INFO > Starting MonitoringEngine
2017-11-08 03:13:16,067 > INFO > Starting MonitoringEngine
2017-11-08 03:15:09,741 > INFO > Starting MonitoringEngine
2017-11-08 03:15:23,295 > INFO > Starting MonitoringEngine
2017-11-08 03:16:43,461 > INFO > Starting MonitoringEngine
2017-11-08 03:24:06,427 > INFO > Starting MonitoringEngine
2017-11-08 03:24:26,957 > INFO > Starting MonitoringEngine
2017-11-08 03:24:35,471 > INFO > Starting MonitoringEngine
2017-11-08 03:24:42,980 > INFO > Starting MonitoringEngine
2017-11-08 03:41:34,450 > INFO > Starting MonitoringEngine
2017-11-08 03:41:50,969 > INFO > Starting MonitoringEngine
2017-11-08 04:19:55,973 > INFO > Starting MonitoringEngine
2017-11-08 04:28:41,481 > INFO > Starting MonitoringEngine
2017-11-08 04:29:07,053 > INFO > Starting MonitoringEngine
2017-11-08 04:29:48,753 > INFO > Starting MonitoringEngine
2017-11-08 04:31:26,490 > INFO > Starting MonitoringEngine
2017-11-08 04:31:31,936 > INFO > Starting MonitoringEngine
2017-11-08 04:31:49,565 > INFO > Starting MonitoringEngine
2017-11-08 04:31:58,184 > INFO > Starting MonitoringEngine
2017-11-08 04:32:17,735 > INFO > Starting MonitoringEngine
2017-11-08 04:32:25,318 > INFO > Starting MonitoringEngine
2017-11-08 04:32:46,031 > INFO > Starting MonitoringEngine
2017-11-08 04:34:34,813 > INFO > Starting MonitoringEngine
2017-11-08 04:34:38,385 > INFO > Starting MonitoringEngine
2017-11-08 04:42:56,055 > INFO > Starting MonitoringEngine
2017-11-08 04:44:45,788 > INFO > Starting MonitoringEngine
2017-11-08 04:52:51,276 > INFO > Starting MonitoringEngine
2017-11-08 05:16:04,190 > INFO > Starting MonitoringEngine
2017-11-08 05:32:33,350 > INFO > Starting MonitoringEngine
2017-11-08 05:32:35,269 > INFO > Starting MonitoringEngine
2017-11-08 05:33:39,420 > INFO > Starting MonitoringEngine
2017-11-08 05:33:54,872 > INFO > Starting MonitoringEngine
2017-11-08 05:34:12,433 > INFO > Starting MonitoringEngine
2017-11-08 05:34:40,044 > INFO > Starting MonitoringEngine
2017-11-08 05:36:15,214 > INFO > Starting MonitoringEngine
2017-11-08 05:36:40,736 > INFO > Starting MonitoringEngine
2017-11-08 06:05:21,989 > INFO > Starting MonitoringEngine
2017-11-08 06:05:38,448 > INFO > Starting MonitoringEngine
2017-11-08 06:06:22,980 > INFO > Starting MonitoringEngine
2017-11-08 06:07:04,496 > INFO > Starting MonitoringEngine
2017-11-08 06:07:12,953 > INFO > Starting MonitoringEngine
2017-11-08 06:13:56,352 > INFO > Starting MonitoringEngine
2017-11-08 06:14:13,832 > INFO > Starting MonitoringEngine
2017-11-08 06:14:30,260 > INFO > Starting MonitoringEngine
2017-11-08 06:14:48,655 > INFO > Starting MonitoringEngine
2017-11-08 06:15:29,198 > INFO > Starting MonitoringEngine
2017-11-08 06:15:44,737 > INFO > Starting MonitoringEngine
2017-11-08 06:18:20,491 > INFO > Starting MonitoringEngine
2017-11-08 06:40:30,710 > INFO > Starting MonitoringEngine
2017-11-08 06:52:37,307 > INFO > Starting MonitoringEngine
2017-11-08 06:52:51,875 > INFO > Starting MonitoringEngine
2017-11-08 06:52:56,427 > INFO > Starting MonitoringEngine
2017-11-08 07:59:47,349 > INFO > Starting MonitoringEngine
2017-11-08 07:59:53,732 > INFO > Starting MonitoringEngine
2017-11-08 08:00:08,216 > INFO > Starting MonitoringEngine
2017-11-08 08:00:18,222 > INFO > Starting MonitoringEngine
2017-11-08 08:05:54,597 > INFO > Starting MonitoringEngine
2017-11-08 08:06:51,666 > INFO > Starting MonitoringEngine
2017-11-08 08:06:56,154 > INFO > Starting MonitoringEngine
2017-11-08 08:11:33,739 > INFO > Starting MonitoringEngine
2017-11-08 08:11:47,181 > INFO > Starting MonitoringEngine
2017-11-08 08:12:53,241 > INFO > Starting MonitoringEngine
2017-11-08 08:13:04,678 > INFO > Starting MonitoringEngine
2017-11-08 08:29:08,905 > INFO > Starting MonitoringEngine
2017-11-08 08:29:10,778 > INFO > Starting MonitoringEngine
2017-11-08 08:36:22,846 > INFO > Starting MonitoringEngine
2017-11-08 08:37:10,886 > INFO > Starting MonitoringEngine
2017-11-08 08:37:36,396 > INFO > Starting MonitoringEngine
2017-11-08 08:37:56,968 > INFO > Starting MonitoringEngine
2017-11-08 08:41:27,158 > INFO > Starting MonitoringEngine
2017-11-08 08:47:47,527 > INFO > Starting MonitoringEngine
2017-11-08 08:50:59,744 > INFO > Starting MonitoringEngine
2017-11-08 08:51:01,545 > INFO > Starting MonitoringEngine
2017-11-08 08:58:47,108 > INFO > Starting MonitoringEngine
2017-11-08 08:59:20,638 > INFO > Starting MonitoringEngine
2017-11-08 09:03:19,156 > INFO > Starting MonitoringEngine
2017-11-08 09:04:11,202 > INFO > Starting MonitoringEngine
2017-11-08 09:05:36,341 > INFO > Starting MonitoringEngine
2017-11-08 09:10:03,960 > INFO > Starting MonitoringEngine
2017-11-08 09:15:02,124 > INFO > Starting MonitoringEngine
2017-11-08 09:15:03,907 > INFO > Starting MonitoringEngine
2017-11-08 09:16:56,517 > INFO > Starting MonitoringEngine
2017-11-08 09:17:29,113 > INFO > Starting MonitoringEngine
2017-11-08 09:22:37,271 > INFO > Starting MonitoringEngine
2017-11-08 09:22:49,703 > INFO > Starting MonitoringEngine
2017-11-08 09:22:53,109 > INFO > Starting MonitoringEngine
2017-11-08 09:25:14,344 > INFO > Starting MonitoringEngine
2017-11-08 10:28:12,065 > INFO > Starting MonitoringEngine
2017-11-08 10:31:54,075 > INFO > Starting MonitoringEngine
2017-11-08 10:32:55,150 > INFO > Starting MonitoringEngine
2017-11-08 10:33:58,337 > INFO > Starting MonitoringEngine
2017-11-08 10:34:10,732 > INFO > Starting MonitoringEngine
2017-11-08 10:34:14,137 > INFO > Starting MonitoringEngine
2017-11-08 10:34:17,768 > INFO > Starting MonitoringEngine
2017-11-08 10:43:14,608 > INFO > Starting MonitoringEngine
2017-11-08 10:43:27,062 > INFO > Starting MonitoringEngine
2017-11-08 10:43:55,598 > INFO > Starting MonitoringEngine
2017-11-08 10:44:03,060 > INFO > Starting MonitoringEngine
2017-11-08 10:46:53,359 > INFO > Starting MonitoringEngine
2017-11-08 10:48:48,543 > INFO > Starting MonitoringEngine
2017-11-08 10:48:53,011 > INFO > Starting MonitoringEngine
2017-11-08 10:49:02,427 > INFO > Starting MonitoringEngine
2017-11-08 10:50:04,563 > INFO > Starting MonitoringEngine
2017-11-08 10:50:10,013 > INFO > Starting MonitoringEngine
2017-11-08 10:50:32,565 > INFO > Starting MonitoringEngine
2017-11-08 10:50:49,998 > INFO > Starting MonitoringEngine
2017-11-08 10:50:59,519 > INFO > Starting MonitoringEngine
2017-11-08 10:53:09,307 > INFO > Starting MonitoringEngine
2017-11-08 10:54:10,329 > INFO > Starting MonitoringEngine
2017-11-08 10:56:05,088 > INFO > Starting MonitoringEngine
2017-11-08 10:56:18,561 > INFO > Starting MonitoringEngine
2017-11-08 10:56:23,046 > INFO > Starting MonitoringEngine
2017-11-08 10:58:27,775 > INFO > Starting MonitoringEngine
2017-11-08 10:58:41,214 > INFO > Starting MonitoringEngine
2017-11-08 10:58:59,887 > INFO > Starting MonitoringEngine
2017-11-08 10:59:24,443 > INFO > Starting MonitoringEngine
2017-11-08 11:02:25,291 > INFO > Starting MonitoringEngine
2017-11-08 11:02:52,892 > INFO > Starting MonitoringEngine
2017-11-08 11:06:01,335 > INFO > Starting MonitoringEngine
2017-11-08 11:08:24,610 > INFO > Starting MonitoringEngine
2017-11-08 11:08:53,112 > INFO > Starting MonitoringEngine
2017-11-08 11:08:58,707 > INFO > Starting MonitoringEngine
2017-11-08 11:09:31,262 > INFO > Starting MonitoringEngine
2017-11-08 11:10:55,483 > INFO > Starting MonitoringEngine
2017-11-08 11:11:15,876 > INFO > Starting MonitoringEngine
2017-11-08 11:11:44,484 > INFO > Starting MonitoringEngine
2017-11-08 11:13:39,238 > INFO > Starting MonitoringEngine
2017-11-08 11:16:17,522 > INFO > Starting MonitoringEngine
2017-11-08 11:16:31,933 > INFO > Starting MonitoringEngine
2017-11-08 11:19:18,246 > INFO > Starting MonitoringEngine
2017-11-08 11:19:24,772 > INFO > Starting MonitoringEngine
2017-11-08 11:19:46,257 > INFO > Starting MonitoringEngine
2017-11-08 11:20:21,832 > INFO > Starting MonitoringEngine
2017-11-08 11:21:47,992 > INFO > Starting MonitoringEngine
2017-11-08 11:22:45,118 > INFO > Starting MonitoringEngine
2017-11-08 11:24:08,237 > INFO > Starting MonitoringEngine
2017-11-08 11:24:13,616 > INFO > Starting MonitoringEngine
2017-11-08 11:24:25,326 > INFO > Starting MonitoringEngine
2017-11-08 11:25:21,390 > INFO > Starting MonitoringEngine
2017-11-08 11:25:32,829 > INFO > Starting MonitoringEngine
2017-11-08 11:25:36,474 > INFO > Starting MonitoringEngine
2017-11-08 11:26:07,009 > INFO > Starting MonitoringEngine
2017-11-08 11:26:20,661 > INFO > Starting MonitoringEngine
2017-11-08 11:27:21,791 > INFO > Starting MonitoringEngine
2017-11-08 11:27:32,274 > INFO > Starting MonitoringEngine
2017-11-08 11:27:39,937 > INFO > Starting MonitoringEngine
2017-11-08 11:30:29,299 > INFO > Starting MonitoringEngine
2017-11-08 11:30:36,789 > INFO > Starting MonitoringEngine
2017-11-08 11:31:01,485 > INFO > Starting MonitoringEngine
2017-11-08 11:31:41,045 > INFO > Starting MonitoringEngine
